cache:
  paths:
    - ./node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

stages:
  - library
  - build
  - test
  - release_staging
  - release_production

before_script:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - yarn install --network-timeout 1000000

core_library:
  image: nampdn/node-alpine-git:11
  stage: library
  tags:
    - docker
    - library
  script:
    - yarn run:core build

build_web:
  image: nampdn/node-alpine-git:11
  stage: build
  tags:
    - docker
    - library
  script:
    - yarn run:web build

build_desktop:
  stage: build
  tags:
    - build-image
  script:
    - yarn build:desktop-docker
